shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.zsh-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.dotfiles-defer]
local = "~/.config/zsh/defer"
use = ["*.zsh"]
apply = ["defer"]

[plugins.dotfiles-sync]
local = "~/.config/zsh/sync"
use = ["*.zsh"]
apply = ["source"]

[plugins.zeno]
github = "yuki-yano/zeno.zsh"
apply = ["defer"]

[plugins.zeno.hooks]
pre = """
export ZENO_ENABLE_SOCK=1
export ZENO_GIT_CAT="bat --color=always"
export ZENO_GIT_TREE="tree"
"""
post = """
bindkey ' '  zeno-auto-snippet
bindkey '^m' zeno-auto-snippet-and-accept-line
bindkey '^i' zeno-completion
bindkey '^x '  zeno-insert-space
bindkey '^x^m' accept-line
bindkey '^x^z' zeno-toggle-auto-snippet
bindkey '^r'   zeno-history-selection
bindkey '^x^s' zeno-insert-snippet
bindkey '^x^f' zeno-ghq-cd
"""

[plugins.anyframe]
github = "mollifier/anyframe"
apply = ["defer"]

[plugins.anyframe.hooks]
post = """
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
bindkey '^f' anyframe-widget-cdr
"""

