snippets:

  - name: todo-txt
    keyword: t
    snippet: todo.sh

  - name: kubectx
    keyword: kcx
    snippet: kubectx

  - name: kubens
    keyword: kns
    snippet: kubens

  - name: kubectl-logs
    keyword: kcl
    snippet: kubectl logs -f {{pod_name}}

  - name: kubectl-pods
    keyword: kcp
    snippet: kubectl get pods

  - name: kubectl-delete-jobs
    keyword: kcdj
    snippet: kubectl delete job

  - name: kubectl-create-jobs
    keyword: kccj
    snippet: kubectl create job --from=cronjob/{{cron_job_name}} {{new_job_name}}

completions:
  - name: todo-done
    patterns:
      - "^todo.sh done $"
    sourceCommand: "todo.sh ls | ghead -n -2"
    callback: "cut -d' ' -f1"

  - name: code
    patterns:
      - "^code $"
    sourceCommand: "ghq list | xargs -I{} echo $(ghq root)'/'{}"

  - name: kubectl-logs
    patterns:
      - "^kubectl logs -f $"
    sourceCommand: "kubectl get pods | tail -n +2"
    callback: "tr ' +' '\t' | cut -f1"

  - name: kubectl-get-jobs
    patterns:
      - "^kubectl delete job $"
    sourceCommand: "kubectl get jobs | tail -n +2"
    callback: "tr ' +' '\t' | cut -f1"

  - name: kubectl-get-cronjobs
    patterns:
      - "^kubectl create job --from=cronjob/$"
    sourceCommand: "kubectl get cronjobs | tail -n +2"
    callback: "tr ' +' '\t' | cut -f1"

